#pragma once


//void 소수찾기();
//void 소수();
//void 소수구하기();
//void 베르트랑공준();
//void 골드바흐의추측();
//void 네번째점();
//void 직각삼각형();
//void 택시기하학();
//void 팩토리얼();
//void 피보나치수5();
//void 블랙잭();
//void 덩치();
//void linkedList();
//void 수정렬하기();
//void 레스터라이즈();
//void 깊은복사();
//void 카카오인형뽑기();
//void 기능개발();
//void 프린터();
//void 더맵게();
//void 다리를지나가는트럭();
//void 소수찾기2();
//void BFS();
//void 큰수만들기();
//void 미로탐색();
//void DFS와BFS();
void 바이러스();